#!/bin/bash

# AI Perfume System - Bedrock Deployment Script
# This script deploys the Lambda functions and updates the CloudFormation stack

set -e

echo "🚀 AI Perfume System - Bedrock Deployment"
echo "=========================================="
echo ""

# Color codes
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Check prerequisites
echo "📋 Checking prerequisites..."

if ! command -v aws &> /dev/null; then
    echo -e "${RED}❌ AWS CLI is not installed${NC}"
    exit 1
fi

if ! command -v node &> /dev/null; then
    echo -e "${RED}❌ Node.js is not installed${NC}"
    exit 1
fi

echo -e "${GREEN}✅ AWS CLI and Node.js found${NC}"
echo ""

# Get AWS account info
echo "🔍 Checking AWS configuration..."
AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
AWS_REGION=${AWS_REGION:-us-east-1}
ENVIRONMENT=${ENVIRONMENT:-dev}

echo "Account ID: $AWS_ACCOUNT_ID"
echo "Region: $AWS_REGION"
echo "Environment: $ENVIRONMENT"
echo ""

# Create S3 bucket for Lambda code
BUCKET_NAME="perfume-lambda-artifacts-${AWS_ACCOUNT_ID}-${AWS_REGION}"
echo "📦 Setting up S3 bucket: $BUCKET_NAME"

if aws s3 ls "s3://$BUCKET_NAME" 2>&1 | grep -q 'NoSuchBucket'; then
    aws s3 mb "s3://$BUCKET_NAME" --region "$AWS_REGION"
    echo -e "${GREEN}✅ Created S3 bucket${NC}"
else
    echo -e "${GREEN}✅ S3 bucket already exists${NC}"
fi
echo ""

# Install Lambda dependencies
echo "📚 Installing Lambda dependencies..."
cd backend/lambda

if [ ! -d node_modules ]; then
    npm install
    echo -e "${GREEN}✅ Dependencies installed${NC}"
else
    echo -e "${GREEN}✅ Dependencies already installed${NC}"
fi
echo ""

# Package Lambda functions
echo "📦 Packaging Lambda functions..."

# Create zip files for each Lambda function
zip -r perfume-api.zip perfume-api.js node_modules/ -q
zip -r photo-analyzer.zip photo-analyzer.js bedrock-utils.js node_modules/ -q
zip -r ai-recommendations.zip ai-recommendations.js bedrock-utils.js node_modules/ -q

echo -e "${GREEN}✅ Lambda functions packaged${NC}"
echo ""

# Upload to S3
echo "☁️  Uploading Lambda functions to S3..."
aws s3 cp perfume-api.zip "s3://$BUCKET_NAME/lambda/" --region "$AWS_REGION"
aws s3 cp photo-analyzer.zip "s3://$BUCKET_NAME/lambda/" --region "$AWS_REGION"
aws s3 cp ai-recommendations.zip "s3://$BUCKET_NAME/lambda/" --region "$AWS_REGION"

echo -e "${GREEN}✅ Uploaded to S3${NC}"
echo ""

# Go back to root
cd ../..

# Update CloudFormation stack
STACK_NAME="perfume-recommendation-system-${ENVIRONMENT}"

echo "🏗️  Deploying CloudFormation stack: $STACK_NAME"
echo ""

# Check if stack exists
if aws cloudformation describe-stacks --stack-name "$STACK_NAME" --region "$AWS_REGION" 2>/dev/null | grep -q "StackStatus"; then
    echo "Updating existing stack..."
    aws cloudformation update-stack \
        --stack-name "$STACK_NAME" \
        --template-body file://backend/template.yaml \
        --parameters ParameterKey=Environment,ParameterValue="$ENVIRONMENT" \
        --capabilities CAPABILITY_NAMED_IAM \
        --region "$AWS_REGION"
else
    echo "Creating new stack..."
    aws cloudformation create-stack \
        --stack-name "$STACK_NAME" \
        --template-body file://backend/template.yaml \
        --parameters ParameterKey=Environment,ParameterValue="$ENVIRONMENT" \
        --capabilities CAPABILITY_NAMED_IAM \
        --region "$AWS_REGION"
fi

echo -e "${YELLOW}⏳ Waiting for stack deployment (this may take a few minutes)...${NC}"
aws cloudformation wait stack-create-complete \
    --stack-name "$STACK_NAME" \
    --region "$AWS_REGION" 2>/dev/null || \
aws cloudformation wait stack-update-complete \
    --stack-name "$STACK_NAME" \
    --region "$AWS_REGION" 2>/dev/null || true

echo ""
echo -e "${GREEN}✅ Stack deployment complete${NC}"
echo ""

# Get stack outputs
echo "📊 Stack Outputs:"
echo "================"
aws cloudformation describe-stacks \
    --stack-name "$STACK_NAME" \
    --region "$AWS_REGION" \
    --query 'Stacks[0].Outputs' \
    --output table

# Create .env file for frontend
echo ""
echo "📝 Generating .env.local file..."

API_URL=$(aws cloudformation describe-stacks \
    --stack-name "$STACK_NAME" \
    --region "$AWS_REGION" \
    --query 'Stacks[0].Outputs[?OutputKey==`ApiUrl`].OutputValue' \
    --output text)

cat > .env.local << EOF
# Auto-generated by deployment script
VITE_API_BASE_URL=${API_URL}
VITE_PHOTO_ANALYSIS_ENDPOINT=${API_URL}/analyze-photo
AWS_REGION=${AWS_REGION}
EOF

echo -e "${GREEN}✅ Created .env.local${NC}"
cat .env.local
echo ""

# Verify Bedrock access
echo "🔐 Checking Bedrock model access..."
if aws bedrock list-foundation-models \
    --region "$AWS_REGION" \
    --query "modelSummaries[?contains(modelId, 'claude-sonnet-4-5')]" | grep -q "claude"; then
    echo -e "${GREEN}✅ Claude Sonnet 4.5 model access confirmed${NC}"
else
    echo -e "${YELLOW}⚠️  Claude 3.5 Sonnet not yet available${NC}"
    echo "   Please go to AWS Bedrock console and request model access"
    echo "   https://console.aws.amazon.com/bedrock/home?region=${AWS_REGION}#/models"
fi
echo ""

# Final instructions
echo "=========================================="
echo -e "${GREEN}🎉 Deployment Complete!${NC}"
echo "=========================================="
echo ""
echo "📖 Next Steps:"
echo ""
echo "1. Verify Bedrock model access (if needed):"
echo "   https://console.aws.amazon.com/bedrock/home?region=${AWS_REGION}#/models"
echo ""
echo "2. Start development server:"
echo "   npm run dev"
echo ""
echo "3. Test photo analyzer:"
echo "   Upload a perfume bottle photo in the Photo Analyzer section"
echo ""
echo "4. Test recommendations:"
echo "   Use the Recommendations page with natural language queries"
echo ""
echo "📚 For more info, see BEDROCK_SETUP.md"
echo ""
