// Full perfume catalog - auto-generated from frontend mockData.ts
const mockPerfumes = [
  {
    id: '1',
    name: 'Aventus',
    brand: 'Creed',
    category: 'chypre',
    notes: {
      top: ['Pineapple', 'Bergamot', 'Black Currant', 'Apple'],
      middle: ['Birch', 'Patchouli', 'Moroccan Jasmine', 'Rose'],
      base: ['Musk', 'Oak Moss', 'Ambergris', 'Vanilla']
    },
    accords: [
      { name: 'fruity', intensity: 100, color: '#FF6B6B' },
      { name: 'citrus', intensity: 85, color: '#FEE440' },
      { name: 'smoky', intensity: 75, color: '#FF8C42' },
      { name: 'woody', intensity: 70, color: '#8B4513' },
      { name: 'fresh', intensity: 65, color: '#4ECDC4' },
      { name: 'musky', intensity: 55, color: '#C8B6E2' }
    ],
    description: 'A legendary fragrance inspired by Napoleon\'s dramatic life. Fruity opening with smoky birch and elegant woods.',
    price: 425,
    image: '/perfume-images/creed-aventus.jpg',
    rating: 4.9,
    reviewCount: 3456,
    gender: 'men',
    seasons: ['spring', 'summer', 'autumn'],
    occasions: ['formal', 'special', 'evening'],
    longevity: 'eternal',
    sillage: 'enormous',
    concentration: 'parfum',
    releaseYear: 2010,
    perfumer: 'Olivier Creed',
    size: 120,
    inStock: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z'
  },
  {
    id: '9',
    name: 'Blue Talisman',
    brand: 'Ex Nihilo',
    category: 'woody',
    notes: {
      top: ['Pear', 'Bergamot', 'Mandarin', 'Ginger'],
      middle: ['Orange Blossom', 'Violet', 'Musk'],
      base: ['Amber', 'Sandalwood', 'Musk']
    },
    description: 'A hypnotic jewel from Ex Nihilo Paris. Juicy citrus and ginger open into a clean woody-amber heart â€” bold, luminous, and magnetically elegant.',
    accords: [
      { name: 'woody', intensity: 90, color: '#8B4513' },
      { name: 'amber', intensity: 80, color: '#D4A96A' },
      { name: 'citrus', intensity: 75, color: '#FEE440' },
      { name: 'musky', intensity: 60, color: '#C8B6E2' },
      { name: 'floral', intensity: 50, color: '#E9C46A' }
    ],
    price: 325,
    image: '/perfume-images/ex-nihilo-blue-talisman.jpg',
    rating: 4.3,
    reviewCount: 654,
    gender: 'unisex',
    seasons: ['spring', 'summer', 'autumn'],
    occasions: ['casual', 'office', 'date'],
    longevity: 'long-lasting',
    sillage: 'moderate',
    concentration: 'edp',
    releaseYear: 2023,
    perfumer: 'Ex Nihilo',
    size: 100,
    inStock: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z'
  },
  {
    id: '21',
    name: 'Silver Mountain Water',
    brand: 'Creed',
    category: 'fresh',
    notes: {
      top: ['Bergamot', 'Green Tea', 'Mandarin'],
      middle: ['Black Currant', 'Galbanum'],
      base: ['Musk', 'Sandalwood', 'Petitgrain']
    },
    accords: [
      {name: 'fresh', intensity: 95, color: '#4ECDC4'},
      {name: 'citrus', intensity: 75, color: '#F4D35E'},
      {name: 'woody', intensity: 55, color: '#8B4513'}
    ],
    description: 'A crystalline aquatic aromatic that captures mountain air and glacier water in a refined Creed bottle.',
    price: 375,
    image: '/perfume-images/creed-silver-mountain-water.jpg',
    rating: 4.8,
    reviewCount: 4225,
    gender: 'unisex',
    seasons: ['spring', 'summer'],
    occasions: ['casual', 'office'],
    longevity: 'long-lasting',
    sillage: 'moderate',
    concentration: 'edp',

    releaseYear: 1999,
    perfumer: 'Olivier Creed',
    size: 100,
    inStock: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z'
  },
  {
    id: '2',
    name: 'Angel\'s Share',
    brand: 'By Kilian',
    category: 'gourmand',
    notes: {
      top: ['Cognac', 'Cinnamon', 'Oak'],
      middle: ['Tonka Bean', 'Praline', 'Hazelnut'],
      base: ['Vanilla', 'Sandalwood', 'Akigalawood']
    },
    description: 'A warm, boozy gourmand fragrance inspired by the angel\'s share of aging cognac. Rich, luxurious, and addictive.',
    accords: [
      { name: 'gourmand', intensity: 100, color: '#C0392B' },
      { name: 'vanilla', intensity: 90, color: '#F4E4C1' },
      { name: 'warm spicy', intensity: 80, color: '#E67E22' },
      { name: 'woody', intensity: 65, color: '#8B4513' },
      { name: 'sweet', intensity: 75, color: '#F1948A' }
    ],
    price: 325,
    image: '/perfume-images/by-kilian-angels-share.jpg',
    rating: 4.7,
    reviewCount: 1876,
    gender: 'unisex',
    seasons: ['autumn', 'winter'],
    occasions: ['evening', 'date', 'special'],
    longevity: 'eternal',
    sillage: 'strong',
    concentration: 'edp',
    releaseYear: 2020,
    perfumer: 'Benoist Lapouza',
    size: 50,
    inStock: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z'
  },
  {
    id: '27',
    name: 'Side Effect',
    brand: 'Initio',
    category: 'woody',
    notes: {
      top: ['Juniper Berries', 'Saffron', 'Cardamom'],
      middle: ['Black Rose', 'Patchouli', 'Dark Chocolate'],
      base: ['Amber', 'Sandalwood', 'Musk']
    },
    accords: [
      { name: 'woody', intensity: 90, color: '#8B4513' },
      { name: 'amber', intensity: 80, color: '#F4A261' },
      { name: 'floral', intensity: 70, color: '#E9C46A' }
    ],
    description: 'A dark, mysterious woody fragrance with saffron and dark rose. Sophisticated, enigmatic, and irresistibly alluring.',
    price: 285,
    image: '/perfume-images/initio-side-effect.jpg',
    rating: 4.4,
    reviewCount: 876,
    gender: 'unisex',
    seasons: ['autumn', 'winter'],
    occasions: ['evening', 'special', 'date'],
    longevity: 'long-lasting',
    sillage: 'moderate',
    concentration: 'edp',
    releaseYear: 2015,
    perfumer: 'Ben Gorham',
    size: 50,
    inStock: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z'
  },
  {
    id: '26',
    name: 'Animalique',
    brand: 'Byredo',
    category: 'oriental',
    notes: {
      top: ['Bergamot', 'Orange Blossom', 'Rose'],
      middle: ['Jasmine', 'Patchouli', 'Sandalwood'],
      base: ['Vanilla', 'Amber', 'Musk', 'Leather']
    },
    accords: [
      { name: 'floral', intensity: 85, color: '#E9C46A' },
      { name: 'amber', intensity: 80, color: '#F4A261' },
      { name: 'woody', intensity: 70, color: '#8B4513' }
    ],
    description: 'A sophisticated oriental floral with animalic undertones. Elegant, sensual, and deeply luxurious with a modern edge.',
    price: 485,
    image: '/perfume-images/byredo-animalique.jpg',
    rating: 4.6,
    reviewCount: 543,
    gender: 'unisex',
    seasons: ['autumn', 'winter'],
    occasions: ['evening', 'special', 'formal'],
    longevity: 'eternal',
    sillage: 'strong',
    concentration: 'edp',
    releaseYear: 2022,
    perfumer: 'Francis Kurkdjian',
    size: 70,
    inStock: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z'
  },
  {
    id: '3',
    name: 'Bleu de Chanel',
    brand: 'Chanel',
    category: 'woody',
    notes: {
      top: ['Grapefruit', 'Lemon', 'Mint', 'Pink Pepper'],
      middle: ['Ginger', 'Nutmeg', 'Jasmine', 'Melon'],
      base: ['Incense', 'Vetiver', 'Cedar', 'Sandalwood', 'Patchouli', 'Labdanum']
    },
    description: 'A woody aromatic fragrance for the man who defies convention. Fresh citrus with warm woods and aromatic herbs.',
    accords: [
      { name: 'woody', intensity: 100, color: '#8B4513' },
      { name: 'fresh', intensity: 85, color: '#4ECDC4' },
      { name: 'citrus', intensity: 75, color: '#FEE440' },
      { name: 'aromatic', intensity: 70, color: '#82C341' },
      { name: 'musky', intensity: 55, color: '#C8B6E2' }
    ],
    price: 155,
    image: '/perfume-images/chanel-bleu-de-chanel.jpg',
    rating: 4.7,
    reviewCount: 2387,
    gender: 'men',
    seasons: ['spring', 'summer', 'autumn'],
    occasions: ['office', 'casual', 'formal'],
    longevity: 'long-lasting',
    sillage: 'moderate',
    concentration: 'edp',
    releaseYear: 2010,
    perfumer: 'Jacques Polge',
    size: 100,
    inStock: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z'
  },
  {
    id: '16',
    name: 'Coco Mademoiselle',
    brand: 'Chanel',
    category: 'floral',
    notes: {
      top: ['Orange', 'Bergamot', 'Grapefruit'],
      middle: ['Rose', 'Jasmine', 'Lychee', 'Italian Jasmine'],
      base: ['Patchouli', 'Vanilla', 'Vetiver', 'White Musk']
    },
    description: 'A modern, elegant fragrance with fresh citrus and floral notes. The perfect balance of sophistication and youthful energy.',
    accords: [
      { name: 'floral', intensity: 100, color: '#E9C46A' },
      { name: 'citrus', intensity: 85, color: '#FEE440' },
      { name: 'musky', intensity: 75, color: '#C8B6E2' },
      { name: 'woody', intensity: 60, color: '#8B4513' },
      { name: 'powdery', intensity: 55, color: '#F5CBA7' }
    ],
    price: 155,
    image: '/perfume-images/chanel-coco-mademoiselle.jpg',
    rating: 4.7,
    reviewCount: 4521,
    gender: 'women',
    seasons: ['spring', 'summer', 'autumn'],
    occasions: ['casual', 'office', 'date'],
    longevity: 'long-lasting',
    sillage: 'moderate',
    concentration: 'edp',
    releaseYear: 2001,
    perfumer: 'Jacques Polge',
    size: 100,
    inStock: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z'
  },
  {
    id: '24',
    name: 'Outlands',
    brand: 'Amouage',
    category: 'oriental',
    notes: {
      top: ['Lemon', 'Bergamot', 'Citrus'],
      middle: ['Patchouli', 'Rose', 'Oud'],
      base: ['Amber', 'Resin', 'Musk', 'Sandalwood']
    },
    accords: [
      { name: 'amber', intensity: 90, color: '#F4A261' },
      { name: 'earthy', intensity: 80, color: '#6B4226' },
      { name: 'citrus', intensity: 60, color: '#FEE440' },
      { name: 'woody', intensity: 75, color: '#8B4513' }
    ],
    description: 'An invitation to journey into the beyond. Bright citrus opens into a lush, humid patchouli before descending into a magnetic amber and resin base.',
    price: 425,
    image: '/perfume-images/amouage-outlands.jpg',
    rating: 4.6,
    reviewCount: 312,
    gender: 'unisex',
    seasons: ['autumn', 'winter'],
    occasions: ['evening', 'special', 'formal'],
    longevity: 'eternal',
    sillage: 'strong',
    concentration: 'edp',
    releaseYear: 2023,
    perfumer: 'CÃ©cile Zarokian',
    size: 100,
    inStock: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z'
  },
  {
    id: '25',
    name: 'Blonde Amber',
    brand: 'Clive Christian',
    category: 'oriental',
    notes: {
      top: ['Rum', 'Frankincense', 'Bitter Orange', 'Cardamom', 'Ginger', 'Grapefruit'],
      middle: ['Blonde Tobacco', 'Tuberose', 'Jasmine', 'Dried Fruits'],
      base: ['Tonka Bean', 'Myrrh', 'Vanilla', 'Labdanum', 'Patchouli', 'Cedar', 'Musk', 'Vetiver']
    },
    accords: [
      { name: 'amber', intensity: 100, color: '#F4A261' },
      { name: 'smoky', intensity: 80, color: '#4A4A4A' },
      { name: 'floral', intensity: 70, color: '#E9C46A' },
      { name: 'woody', intensity: 65, color: '#8B4513' }
    ],
    description: 'Art Deco decadence in a bottle. Warm amber spiced with aromatic blonde tobacco, a riot of florals and dried fruits â€” indulgent, sensuous, and deeply luxurious.',
    price: 525,
    image: '/perfume-images/clive-christian-blonde-amber.jpg',
    rating: 4.7,
    reviewCount: 287,
    gender: 'unisex',
    seasons: ['autumn', 'winter'],
    occasions: ['evening', 'special', 'date'],
    longevity: 'eternal',
    sillage: 'strong',
    concentration: 'edp',
    releaseYear: 2021,
    perfumer: 'Clive Christian',
    size: 50,
    inStock: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z'
  },
  {
    id: '4',
    name: 'Sauvage',
    brand: 'Dior',
    category: 'fresh',
    notes: {
      top: ['Calabrian Bergamot', 'Pepper'],
      middle: ['Sichuan Pepper', 'Lavender', 'Pink Pepper', 'Vetiver', 'Patchouli', 'Geranium', 'Elemi'],
      base: ['Ambroxan', 'Cedar', 'Labdanum']
    },
    description: 'A wild and noble fragrance. Fresh bergamot with spicy pepper and woody ambroxan create a magnetic masculinity.',
    accords: [
      { name: 'fresh spicy', intensity: 100, color: '#82C341' },
      { name: 'woody', intensity: 85, color: '#8B4513' },
      { name: 'aromatic', intensity: 75, color: '#5DADE2' },
      { name: 'citrus', intensity: 65, color: '#FEE440' },
      { name: 'musky', intensity: 55, color: '#C8B6E2' }
    ],
    price: 135,
    image: '/perfume-images/dior-sauvage.jpg',
    rating: 4.6,
    reviewCount: 2934,
    gender: 'men',
    seasons: ['spring', 'summer', 'autumn'],
    occasions: ['casual', 'office', 'date'],
    longevity: 'long-lasting',
    sillage: 'strong',
    concentration: 'edt',
    releaseYear: 2015,
    perfumer: 'FranÃ§ois Demachy',
    size: 100,
    inStock: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z'
  },
  {
    id: '17',
    name: "J'adore",
    brand: 'Dior',
    category: 'floral',
    notes: {
      top: ['Pear', 'Melon', 'Bergamot', 'Mandarin Orange'],
      middle: ['Jasmine', 'Lily of the Valley', 'Tuberose', 'Freesia', 'Rose', 'Orchid', 'Plum'],
      base: ['Musk', 'Vanilla', 'Blackberry', 'Cedar']
    },
    description: 'A luminous floral bouquet. An ode to women, their audacity, and their beauty. Sensual and sophisticated.',
    accords: [
      { name: 'floral', intensity: 100, color: '#E9C46A' },
      { name: 'fruity', intensity: 80, color: '#FF6B6B' },
      { name: 'musky', intensity: 70, color: '#C8B6E2' },
      { name: 'powdery', intensity: 60, color: '#F5CBA7' },
      { name: 'sweet', intensity: 50, color: '#F1948A' }
    ],
    price: 135,
    image: '/perfume-images/dior-jadore.jpg',
    rating: 4.6,
    reviewCount: 3892,
    gender: 'women',
    seasons: ['spring', 'summer'],
    occasions: ['evening', 'special', 'date'],
    longevity: 'long-lasting',
    sillage: 'strong',
    concentration: 'edp',
    releaseYear: 1999,
    perfumer: 'Calice Becker',
    size: 100,
    inStock: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z'
  },
  {
    id: '28',
    name: 'Purpose 50',
    brand: 'Amouage',
    category: 'floral',
    notes: {
      top: ['Black Currant', 'Bergamot', 'Rose'],
      middle: ['Rose', 'Jasmine', 'Patchouli'],
      base: ['Amber', 'Patchouli', 'Sandalwood']
    },
    accords: [
      { name: 'floral', intensity: 95, color: '#E9C46A' },
      { name: 'fruity', intensity: 75, color: '#FF6B6B' },
      { name: 'woody', intensity: 70, color: '#8B4513' }
    ],
    description: 'A masterpiece of rose and blackcurrant. Elegant, sophisticated, and timelessly beautiful - a true portrait of feminine grace.',
    price: 395,
    image: '/perfume-images/amouage-purpose-50.jpg',
    rating: 4.8,
    reviewCount: 1234,
    gender: 'women',
    seasons: ['spring', 'summer', 'autumn'],
    occasions: ['evening', 'special', 'formal'],
    longevity: 'eternal',
    sillage: 'strong',
    concentration: 'edp',
    releaseYear: 2010,
    perfumer: 'Dominique Ropion',
    size: 50,
    inStock: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z'
  },
  {
    id: '14',
    name: 'Bianco Latte',
    brand: 'Giardini di Toscana',
    category: 'gourmand',
    notes: {
      top: ['Milk', 'Honey', 'Star Anise'],
      middle: ['White Chocolate', 'Coconut', 'Rice'],
      base: ['Vanilla', 'Sandalwood', 'White Musk']
    },
    description: 'A creamy, milky gourmand fragrance. Soft, comforting, and irresistibly sweet like warm milk and honey.',
    accords: [
      { name: 'gourmand', intensity: 100, color: '#C0392B' },
      { name: 'sweet', intensity: 90, color: '#F1948A' },
      { name: 'vanilla', intensity: 85, color: '#F4E4C1' },
      { name: 'powdery', intensity: 65, color: '#F5CBA7' },
      { name: 'musky', intensity: 50, color: '#C8B6E2' }
    ],
    price: 165,
    image: '/perfume-images/giardini-bianco-latte.jpg',
    rating: 4.4,
    reviewCount: 678,
    gender: 'unisex',
    seasons: ['autumn', 'winter', 'spring'],
    occasions: ['casual', 'date', 'evening'],
    longevity: 'long-lasting',
    sillage: 'moderate',
    concentration: 'edp',
    releaseYear: 2018,
    perfumer: 'Silvia Monti',
    size: 100,
    inStock: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z'
  },
  {
    id: '15',
    name: 'Vanilla Powder',
    brand: 'Giardini di Toscana',
    category: 'gourmand',
    notes: {
      top: ['Vanilla', 'Powdery Notes', 'Bergamot'],
      middle: ['Iris', 'Heliotrope', 'Almond'],
      base: ['Vanilla', 'Sandalwood', 'White Musk', 'Tonka Bean']
    },
    description: 'A soft, powdery vanilla fragrance. Delicate, comforting, and elegantly sweet like fine vanilla powder.',
    accords: [
      { name: 'vanilla', intensity: 100, color: '#F4E4C1' },
      { name: 'powdery', intensity: 90, color: '#F5CBA7' },
      { name: 'sweet', intensity: 80, color: '#F1948A' },
      { name: 'floral', intensity: 60, color: '#E9C46A' },
      { name: 'musky', intensity: 50, color: '#C8B6E2' }
    ],
    price: 165,
    image: '/perfume-images/giardini-vanilla-powder.jpg',
    rating: 4.3,
    reviewCount: 543,
    gender: 'unisex',
    seasons: ['autumn', 'winter', 'spring'],
    occasions: ['casual', 'date', 'office'],
    longevity: 'long-lasting',
    sillage: 'moderate',
    concentration: 'edp',
    releaseYear: 2018,
    perfumer: 'Silvia Monti',
    size: 100,
    inStock: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z'
  },
  {
    id: '19',
    name: 'La Vie Est Belle',
    brand: 'LancÃ´me',
    category: 'gourmand',
    notes: {
      top: ['Black Currant', 'Pear'],
      middle: ['Iris', 'Jasmine', 'Orange Blossom'],
      base: ['Praline', 'Vanilla', 'Patchouli', 'Tonka Bean']
    },
    description: 'Life is beautiful. A sweet, sophisticated gourmand with iris and praline. Happiness in a bottle.',
    accords: [
      { name: 'gourmand', intensity: 100, color: '#C0392B' },
      { name: 'sweet', intensity: 85, color: '#F1948A' },
      { name: 'floral', intensity: 75, color: '#E9C46A' },
      { name: 'vanilla', intensity: 70, color: '#F4E4C1' },
      { name: 'powdery', intensity: 55, color: '#F5CBA7' }
    ],
    price: 135,
    image: '/perfume-images/lancome-la-vie-est-belle.jpg',
    rating: 4.4,
    reviewCount: 4167,
    gender: 'women',
    seasons: ['autumn', 'winter', 'spring'],
    occasions: ['casual', 'office', 'date'],
    longevity: 'long-lasting',
    sillage: 'moderate',
    concentration: 'edp',
    releaseYear: 2012,
    perfumer: 'Olivier Polge, Dominique Ropion, Anne Flipo',
    size: 100,
    inStock: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z'
  },
  {
    id: '10',
    name: 'Imagination',
    brand: 'Louis Vuitton',
    category: 'woody',
    notes: {
      top: ['Bergamot', 'Ginger', 'Pink Pepper'],
      middle: ['Tea', 'Neroli', 'Orange Blossom'],
      base: ['Ambroxan', 'Sandalwood', 'Musk']
    },
    description: 'A sophisticated and modern woody fragrance. Clean, refined, and effortlessly luxurious with a contemporary edge.',
    accords: [
      { name: 'woody', intensity: 95, color: '#8B4513' },
      { name: 'fresh', intensity: 80, color: '#4ECDC4' },
      { name: 'citrus', intensity: 70, color: '#FEE440' },
      { name: 'musky', intensity: 65, color: '#C8B6E2' },
      { name: 'spicy', intensity: 50, color: '#E67E22' }
    ],
    price: 285,
    image: '/perfume-images/lv-imagination.jpg',
    rating: 4.4,
    reviewCount: 789,
    gender: 'men',
    seasons: ['spring', 'summer', 'autumn'],
    occasions: ['office', 'casual', 'formal'],
    longevity: 'long-lasting',
    sillage: 'moderate',
    concentration: 'edp',
    releaseYear: 2018,
    perfumer: 'Jacques Cavallier Belletrud',
    size: 100,
    inStock: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z'
  },
  {
    id: '23',
    name: 'Ombre Nomade',
    brand: 'Louis Vuitton',
    category: 'oriental',
    notes: {
      top: ['Incense', 'Raspberry'],
      middle: ['Oud Wood', 'Rose', 'Benzoin'],
      base: ['Amberwood', 'Leather', 'Musk']
    },
    accords: [
      { name: 'oud', intensity: 100, color: '#6B3A2A' },
      { name: 'smoky', intensity: 85, color: '#4A4A4A' },
      { name: 'fruity', intensity: 65, color: '#E63946' },
      { name: 'woody', intensity: 80, color: '#8B4513' }
    ],
    description: 'A rebellious oud masterpiece. Smoky incense and sweet raspberry open into precious oud and rose, deepening into a warm, enveloping benzoin and amberwood base.',
    price: 480,
    image: '/perfume-images/lv-ombre-nomade.jpg',
    rating: 4.8,
    reviewCount: 1876,
    gender: 'unisex',
    seasons: ['autumn', 'winter'],
    occasions: ['evening', 'special', 'date'],
    longevity: 'eternal',
    sillage: 'enormous',
    concentration: 'edp',
    releaseYear: 2018,
    perfumer: 'Jacques Cavallier Belletrud',
    size: 100,
    inStock: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z'
  },
  {
    id: '11',
    name: 'Pacific Chill',
    brand: 'Louis Vuitton',
    category: 'fresh',
    notes: {
      top: ['Ginger', 'Bergamot', 'Mandarin'],
      middle: ['Mint', 'Eucalyptus', 'Lavender'],
      base: ['Sandalwood', 'Cedar', 'Musk']
    },
    description: 'A refreshing and invigorating fragrance inspired by ocean breezes. Cool, clean, and utterly relaxing.',
    accords: [
      { name: 'fresh', intensity: 100, color: '#4ECDC4' },
      { name: 'citrus', intensity: 80, color: '#FEE440' },
      { name: 'aromatic', intensity: 70, color: '#82C341' },
      { name: 'woody', intensity: 55, color: '#8B4513' },
      { name: 'musky', intensity: 45, color: '#C8B6E2' }
    ],
    price: 285,
    image: '/perfume-images/lv-pacific-chill.jpg',
    rating: 4.2,
    reviewCount: 567,
    gender: 'unisex',
    seasons: ['spring', 'summer'],
    occasions: ['casual', 'sport', 'office'],
    longevity: 'moderate',
    sillage: 'moderate',
    concentration: 'edp',
    releaseYear: 2018,
    perfumer: 'Jacques Cavallier Belletrud',
    size: 100,
    inStock: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z'
  },
  {
    id: '22',
    name: 'Stellar Times',
    brand: 'Louis Vuitton',
    category: 'oriental',
    notes: {
      top: ['Orange Blossom', 'Bergamot', 'Mandarin'],
      middle: ['Peru Balsam', 'Rose', 'Jasmine'],
      base: ['Amber', 'Sandalwood', 'Musk', 'Vanilla']
    },
    accords: [
      { name: 'amber', intensity: 95, color: '#F4A261' },
      { name: 'floral', intensity: 75, color: '#E9C46A' },
      { name: 'woody', intensity: 60, color: '#8B4513' }
    ],
    description: 'A subliminal journey through time. Golden orange blossom swirls on a transfigured amber accord, evoking legendary temples and marvellous fountains.',
    price: 620,
    image: '/perfume-images/lv-stellar-times.jpg',
    rating: 4.7,
    reviewCount: 432,
    gender: 'unisex',
    seasons: ['autumn', 'winter'],
    occasions: ['evening', 'special', 'formal'],
    longevity: 'eternal',
    sillage: 'strong',
    concentration: 'edp',
    releaseYear: 2019,
    perfumer: 'Jacques Cavallier Belletrud',
    size: 100,
    inStock: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z'
  },
  {
    id: '5',
    name: 'Althair',
    brand: 'Parfums de Marly',
    category: 'oriental',
    notes: {
      top: ['Cardamom', 'Cinnamon', 'Orange', 'Bergamot'],
      middle: ['Bourbon Vanilla', 'Rose', 'Jasmine'],
      base: ['Vanilla', 'Sandalwood', 'Amberwood', 'Guaiac Wood', 'Musk']
    },
    description: 'A sophisticated oriental fragrance with warm spices and creamy vanilla. Elegant, refined, and utterly captivating.',
    accords: [
      { name: 'warm spicy', intensity: 100, color: '#E67E22' },
      { name: 'vanilla', intensity: 85, color: '#F4E4C1' },
      { name: 'woody', intensity: 75, color: '#8B4513' },
      { name: 'floral', intensity: 60, color: '#E9C46A' },
      { name: 'sweet', intensity: 55, color: '#F1948A' }
    ],
    price: 225,
    image: '/perfume-images/pdm-althair.jpg',
    rating: 4.5,
    reviewCount: 1234,
    gender: 'men',
    seasons: ['autumn', 'winter'],
    occasions: ['evening', 'date', 'formal'],
    longevity: 'long-lasting',
    sillage: 'strong',
    concentration: 'edp',
    releaseYear: 2019,
    perfumer: 'Hamid Merati-Kashani',
    size: 125,
    inStock: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z'
  },
  {
    id: '12',
    name: 'L\'Homme',
    brand: 'Prada',
    category: 'fresh',
    notes: {
      top: ['Neroli', 'Black Pepper', 'Cardamom'],
      middle: ['Iris', 'Violet', 'Geranium'],
      base: ['Sandalwood', 'Cedar', 'Patchouli']
    },
    description: 'A modern interpretation of classic masculinity. Fresh, sophisticated, and elegantly refined.',
    accords: [
      { name: 'powdery', intensity: 90, color: '#F5CBA7' },
      { name: 'floral', intensity: 80, color: '#E9C46A' },
      { name: 'woody', intensity: 75, color: '#8B4513' },
      { name: 'fresh', intensity: 65, color: '#4ECDC4' },
      { name: 'musky', intensity: 55, color: '#C8B6E2' }
    ],
    price: 95,
    image: '/perfume-images/prada-lhomme.jpg',
    rating: 4.3,
    reviewCount: 1456,
    gender: 'men',
    seasons: ['spring', 'summer', 'autumn'],
    occasions: ['office', 'casual', 'formal'],
    longevity: 'moderate',
    sillage: 'moderate',
    concentration: 'edt',
    releaseYear: 2016,
    perfumer: 'Daniela Andrier',
    size: 100,
    inStock: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z'
  },
  {
    id: '20',
    name: 'Flowerbomb',
    brand: 'Viktor & Rolf',
    category: 'floral',
    notes: {
      top: ['Tea', 'Bergamot', 'Osmanthus'],
      middle: ['Sambac Jasmine', 'Orchid', 'Freesia', 'Rose'],
      base: ['Patchouli', 'Musk', 'Amber']
    },
    description: 'An explosive floral bouquet. A powerful, positive, addictive fragrance. Like a burst of flowers.',
    accords: [
      { name: 'floral', intensity: 100, color: '#E9C46A' },
      { name: 'sweet', intensity: 80, color: '#F1948A' },
      { name: 'woody', intensity: 65, color: '#8B4513' },
      { name: 'musky', intensity: 60, color: '#C8B6E2' },
      { name: 'powdery', intensity: 50, color: '#F5CBA7' }
    ],
    price: 155,
    image: '/perfume-images/viktor-rolf-flowerbomb.jpg',
    rating: 4.6,
    reviewCount: 3745,
    gender: 'women',
    seasons: ['spring', 'autumn', 'winter'],
    occasions: ['evening', 'special', 'date'],
    longevity: 'eternal',
    sillage: 'strong',
    concentration: 'edp',
    releaseYear: 2005,
    perfumer: 'Olivier Polge, Carlos Benaim, Domitille Bertier',
    size: 100,
    inStock: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z'
  },
  {
    id: '13',
    name: 'Naxos',
    brand: 'Xerjoff',
    category: 'oriental',
    notes: {
      top: ['Bergamot', 'Lemon', 'Lavender'],
      middle: ['Cinnamon', 'Honey', 'Cashmeran'],
      base: ['Vanilla', 'Tobacco Leaf', 'Sandalwood']
    },
    description: 'A luxurious oriental fragrance with Mediterranean influences. Warm, sophisticated, and utterly captivating.',
    accords: [
      { name: 'tobacco', intensity: 100, color: '#7D5A3C' },
      { name: 'vanilla', intensity: 90, color: '#F4E4C1' },
      { name: 'warm spicy', intensity: 80, color: '#E67E22' },
      { name: 'woody', intensity: 70, color: '#8B4513' },
      { name: 'sweet', intensity: 60, color: '#F1948A' }
    ],
    price: 225,
    image: '/perfume-images/xerjoff-naxos.jpg',
    rating: 4.6,
    reviewCount: 892,
    gender: 'unisex',
    seasons: ['autumn', 'winter'],
    occasions: ['evening', 'date', 'special'],
    longevity: 'eternal',
    sillage: 'strong',
    concentration: 'edp',
    releaseYear: 2015,
    perfumer: 'Chris Maurice',
    size: 100,
    inStock: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z'
  },
  {
    id: '6',
    name: 'Babycat',
    brand: 'Yves Saint Laurent',
    category: 'gourmand',
    notes: {
      top: ['Black Currant', 'Ginger'],
      middle: ['Peach', 'Fig', 'Carrot Seeds'],
      base: ['Ambroxan', 'Cashmeran', 'Ambergris']
    },
    description: 'A playful and modern gourmand fragrance. Sweet, fruity, and irresistibly charming with a contemporary edge.',
    accords: [
      { name: 'vanilla', intensity: 100, color: '#F4E4C1' },
      { name: 'sweet', intensity: 90, color: '#F1948A' },
      { name: 'musky', intensity: 75, color: '#C8B6E2' },
      { name: 'woody', intensity: 60, color: '#8B4513' },
      { name: 'fruity', intensity: 55, color: '#FF6B6B' }
    ],
    price: 280,
    image: '/perfume-images/ysl-babycat.jpg',
    rating: 4.3,
    reviewCount: 987,
    gender: 'unisex',
    seasons: ['spring', 'summer'],
    occasions: ['casual', 'date', 'office'],
    longevity: 'moderate',
    sillage: 'moderate',
    concentration: 'edp',
    releaseYear: 2021,
    perfumer: 'Dora Baghriche',
    size: 75,
    inStock: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z'
  },
  {
    id: '18',
    name: 'Black Opium',
    brand: 'Yves Saint Laurent',
    category: 'oriental',
    notes: {
      top: ['Pink Pepper', 'Orange Blossom', 'Pear'],
      middle: ['Coffee', 'Jasmine', 'Bitter Almond', 'Licorice'],
      base: ['Vanilla', 'Patchouli', 'Cedar', 'Cashmere Wood']
    },
    description: 'A seductive, addictive fragrance. Coffee and vanilla create an intoxicating blend. Bold, modern, and unforgettable.',
    accords: [
      { name: 'coffee', intensity: 100, color: '#6F4E37' },
      { name: 'vanilla', intensity: 90, color: '#F4E4C1' },
      { name: 'sweet', intensity: 80, color: '#F1948A' },
      { name: 'floral', intensity: 65, color: '#E9C46A' },
      { name: 'warm spicy', intensity: 55, color: '#E67E22' }
    ],
    price: 163,
    image: '/perfume-images/ysl-black-opium.jpg',
    rating: 4.5,
    reviewCount: 5234,
    gender: 'women',
    seasons: ['autumn', 'winter'],
    occasions: ['evening', 'special', 'date'],
    longevity: 'eternal',
    sillage: 'strong',
    concentration: 'edp',
    releaseYear: 2014,
    perfumer: 'Nathalie Lorson, Marie Salamagne, Olivier Cresp, Honorine Blanc',
    size: 90,
    inStock: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z'
  },
  {
    id: '8',
    name: 'Caban',
    brand: 'Yves Saint Laurent',
    category: 'woody',
    notes: {
      top: ['Ginger', 'Black Pepper', 'Bergamot'],
      middle: ['Patchouli', 'Sandalwood', 'Cedar'],
      base: ['Vanilla', 'Benzoin', 'Labdanum']
    },
    description: 'A warm and enveloping woody fragrance. Sophisticated, masculine, and deeply comforting like a cashmere coat.',
    accords: [
      { name: 'woody', intensity: 100, color: '#8B4513' },
      { name: 'warm spicy', intensity: 85, color: '#E67E22' },
      { name: 'vanilla', intensity: 75, color: '#F4E4C1' },
      { name: 'amber', intensity: 65, color: '#D4A96A' },
      { name: 'musky', intensity: 55, color: '#C8B6E2' }
    ],
    price: 250,
    image: '/perfume-images/ysl-caban.jpg',
    rating: 4.2,
    reviewCount: 876,
    gender: 'men',
    seasons: ['autumn', 'winter'],
    occasions: ['evening', 'formal', 'date'],
    longevity: 'long-lasting',
    sillage: 'moderate',
    concentration: 'edp',
    releaseYear: 2021,
    perfumer: 'Dora Baghriche',
    size: 100,
    inStock: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z'
  },
  {
    id: '7',
    name: 'Y',
    brand: 'Yves Saint Laurent',
    category: 'fresh',
    notes: {
      top: ['Apple', 'Ginger', 'Bergamot', 'Lemon'],
      middle: ['Sage', 'Juniper Berries', 'Geranium'],
      base: ['Amberwood', 'Tonka Bean', 'Cedar', 'Vetiver', 'Olibanum']
    },
    description: 'A fresh and modern fragrance for the contemporary man. Crisp, clean, and effortlessly sophisticated.',
    accords: [
      { name: 'fresh', intensity: 95, color: '#4ECDC4' },
      { name: 'woody', intensity: 80, color: '#8B4513' },
      { name: 'citrus', intensity: 70, color: '#FEE440' },
      { name: 'aromatic', intensity: 65, color: '#82C341' },
      { name: 'amber', intensity: 55, color: '#D4A96A' }
    ],
    price: 115,
    image: '/perfume-images/ysl-y.jpg',
    rating: 4.4,
    reviewCount: 1567,
    gender: 'men',
    seasons: ['spring', 'summer', 'autumn'],
    occasions: ['casual', 'office', 'sport'],
    longevity: 'moderate',
    sillage: 'moderate',
    concentration: 'edt',
    releaseYear: 2017,
    perfumer: 'Dominique Ropion',
    size: 100,
    inStock: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z'
  },
  // â”€â”€ Stronger With You line (top 3) â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  {
    id: '29',
    name: 'Stronger With You',
    brand: 'Emporio Armani',
    category: 'oriental',
    notes: {
      top: ['Pink Pepper', 'Cardamom', 'Violet Leaf'],
      middle: ['Chestnut', 'Sage', 'Lavender'],
      base: ['Vanilla', 'Sandalwood', 'Musk', 'Cashmere Wood']
    },
    accords: [
      { name: 'warm spicy', intensity: 100, color: '#E67E22' },
      { name: 'vanilla', intensity: 85, color: '#F4E4C1' },
      { name: 'woody', intensity: 70, color: '#8B4513' },
      { name: 'sweet', intensity: 65, color: '#F1948A' }
    ],
    description: 'The original and iconic. A warm, spicy-sweet fragrance built around chestnut and vanilla â€” bold, seductive, and irresistibly modern.',
    price: 95,
    image: '/perfume-images/armani-stronger-with-you.jpg',
    rating: 4.5,
    reviewCount: 8234,
    gender: 'men',
    seasons: ['autumn', 'winter'],
    occasions: ['date', 'evening', 'casual'],
    longevity: 'long-lasting',
    sillage: 'strong',
    concentration: 'edt',
    releaseYear: 2017,
    perfumer: 'Quentin Bisch',
    size: 100,
    inStock: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z'
  },
  {
    id: '30',
    name: 'Stronger With You Intensely',
    brand: 'Emporio Armani',
    category: 'oriental',
    notes: {
      top: ['Pink Pepper', 'Cardamom'],
      middle: ['Chestnut', 'Lavender', 'Sage'],
      base: ['Vanilla', 'Tonka Bean', 'Musk', 'Amber']
    },
    accords: [
      { name: 'vanilla', intensity: 100, color: '#F4E4C1' },
      { name: 'warm spicy', intensity: 90, color: '#E67E22' },
      { name: 'sweet', intensity: 80, color: '#F1948A' },
      { name: 'woody', intensity: 65, color: '#8B4513' }
    ],
    description: 'A richer, deeper take on the original. More vanilla, more tonka, more intensity â€” perfect for cold evenings and special occasions.',
    price: 115,
    image: '/perfume-images/armani-stronger-with-you-intensely.jpg',
    rating: 4.7,
    reviewCount: 6543,
    gender: 'men',
    seasons: ['autumn', 'winter'],
    occasions: ['evening', 'date', 'special'],
    longevity: 'eternal',
    sillage: 'enormous',
    concentration: 'edp',
    releaseYear: 2019,
    perfumer: 'Quentin Bisch',
    size: 100,
    inStock: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z'
  },
  {
    id: '31',
    name: 'Stronger With You Only',
    brand: 'Emporio Armani',
    category: 'fresh',
    notes: {
      top: ['Grapefruit'],
      middle: ['Lavender', 'Geranium'],
      base: ['Vanilla', 'Chestnut', 'Labdanum']
    },
    accords: [
      { name: 'fresh', intensity: 90, color: '#4ECDC4' },
      { name: 'vanilla', intensity: 75, color: '#F4E4C1' },
      { name: 'citrus', intensity: 70, color: '#FEE440' },
      { name: 'woody', intensity: 55, color: '#8B4513' }
    ],
    description: 'The fresh, daytime version of the Stronger With You family. Grapefruit and lavender open into the signature chestnut-vanilla base â€” lighter and more versatile.',
    price: 95,
    image: '/perfume-images/armani-stronger-with-you-only.jpg',
    rating: 4.3,
    reviewCount: 3421,
    gender: 'men',
    seasons: ['spring', 'summer', 'autumn'],
    occasions: ['casual', 'office', 'date'],
    longevity: 'moderate',
    sillage: 'moderate',
    concentration: 'edt',
    releaseYear: 2022,
    perfumer: 'Quentin Bisch',
    size: 100,
    inStock: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z'
  },
  // â”€â”€ JPG Le Male line (top 5) â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  {
    id: '32',
    name: 'Le Male',
    brand: 'Jean Paul Gaultier',
    category: 'fresh',
    notes: {
      top: ['Mint', 'Bergamot', 'Cardamom'],
      middle: ['Lavender', 'Cumin', 'Cinnamon'],
      base: ['Vanilla', 'Sandalwood', 'Amber', 'Musk']
    },
    accords: [
      { name: 'aromatic', intensity: 100, color: '#82C341' },
      { name: 'vanilla', intensity: 85, color: '#F4E4C1' },
      { name: 'fresh', intensity: 75, color: '#4ECDC4' },
      { name: 'warm spicy', intensity: 65, color: '#E67E22' }
    ],
    description: 'The iconic original. A timeless masculine fragrance combining fresh mint and lavender with a warm vanilla and sandalwood base â€” one of the best-selling men\'s fragrances of all time.',
    price: 85,
    image: '/perfume-images/jpg-le-male.jpg',
    rating: 4.6,
    reviewCount: 15234,
    gender: 'men',
    seasons: ['spring', 'summer', 'autumn'],
    occasions: ['casual', 'date', 'office'],
    longevity: 'long-lasting',
    sillage: 'strong',
    concentration: 'edt',
    releaseYear: 1995,
    perfumer: 'Francis Kurkdjian',
    size: 125,
    inStock: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z'
  },
  {
    id: '33',
    name: 'Le Male Elixir',
    brand: 'Jean Paul Gaultier',
    category: 'oriental',
    notes: {
      top: ['Lavender', 'Cardamom'],
      middle: ['Vanilla', 'Tonka Bean'],
      base: ['Amber', 'Musk', 'Sandalwood']
    },
    accords: [
      { name: 'vanilla', intensity: 100, color: '#F4E4C1' },
      { name: 'warm spicy', intensity: 90, color: '#E67E22' },
      { name: 'sweet', intensity: 85, color: '#F1948A' },
      { name: 'aromatic', intensity: 70, color: '#82C341' }
    ],
    description: 'The most intense and seductive version of Le Male. A rich, gourmand-oriental powerhouse with lavender and tonka bean â€” dark, addictive, and unforgettable.',
    price: 145,
    image: '/perfume-images/jpg-le-male-elixir.jpg',
    rating: 4.8,
    reviewCount: 7823,
    gender: 'men',
    seasons: ['autumn', 'winter'],
    occasions: ['evening', 'date', 'special'],
    longevity: 'eternal',
    sillage: 'enormous',
    concentration: 'parfum',
    releaseYear: 2023,
    perfumer: 'Quentin Bisch',
    size: 125,
    inStock: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z'
  },
  {
    id: '34',
    name: 'Le Male Le Parfum',
    brand: 'Jean Paul Gaultier',
    category: 'oriental',
    notes: {
      top: ['Mint', 'Bergamot'],
      middle: ['Lavender', 'Vanilla'],
      base: ['Tonka Bean', 'Amber', 'Musk']
    },
    accords: [
      { name: 'aromatic', intensity: 95, color: '#82C341' },
      { name: 'vanilla', intensity: 85, color: '#F4E4C1' },
      { name: 'sweet', intensity: 75, color: '#F1948A' },
      { name: 'musky', intensity: 65, color: '#C8B6E2' }
    ],
    description: 'A more refined, intense interpretation of the classic Le Male. Deeper vanilla and tonka with the signature mint-lavender opening â€” sophisticated and long-lasting.',
    price: 120,
    image: '/perfume-images/jpg-le-male-le-parfum.jpg',
    rating: 4.6,
    reviewCount: 5432,
    gender: 'men',
    seasons: ['autumn', 'winter', 'spring'],
    occasions: ['evening', 'date', 'formal'],
    longevity: 'eternal',
    sillage: 'strong',
    concentration: 'edp',
    releaseYear: 2021,
    perfumer: 'Quentin Bisch',
    size: 125,
    inStock: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z'
  },
  {
    id: '35',
    name: 'Le Beau',
    brand: 'Jean Paul Gaultier',
    category: 'fresh',
    notes: {
      top: ['Bergamot', 'Coconut'],
      middle: ['Vetiver', 'Iris'],
      base: ['Tonka Bean', 'Sandalwood', 'Musk']
    },
    accords: [
      { name: 'fresh', intensity: 95, color: '#4ECDC4' },
      { name: 'woody', intensity: 80, color: '#8B4513' },
      { name: 'citrus', intensity: 70, color: '#FEE440' },
      { name: 'sweet', intensity: 60, color: '#F1948A' }
    ],
    description: 'A fresh, tropical masculine fragrance. Coconut and bergamot open into a clean vetiver heart with a warm tonka base â€” effortlessly cool and modern.',
    price: 95,
    image: '/perfume-images/jpg-le-beau.jpg',
    rating: 4.5,
    reviewCount: 4321,
    gender: 'men',
    seasons: ['spring', 'summer'],
    occasions: ['casual', 'sport', 'date'],
    longevity: 'long-lasting',
    sillage: 'moderate',
    concentration: 'edt',
    releaseYear: 2019,
    perfumer: 'Quentin Bisch',
    size: 125,
    inStock: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z'
  },
  {
    id: '36',
    name: 'Le Male Essence de Parfum',
    brand: 'Jean Paul Gaultier',
    category: 'oriental',
    notes: {
      top: ['Mint', 'Lavender'],
      middle: ['Iris', 'Cumin'],
      base: ['Vanilla', 'Amber', 'Sandalwood', 'Musk']
    },
    accords: [
      { name: 'aromatic', intensity: 90, color: '#82C341' },
      { name: 'vanilla', intensity: 80, color: '#F4E4C1' },
      { name: 'powdery', intensity: 70, color: '#F5CBA7' },
      { name: 'musky', intensity: 65, color: '#C8B6E2' }
    ],
    description: 'A concentrated, powdery-oriental take on Le Male. Iris and cumin add depth to the classic mint-lavender-vanilla DNA â€” elegant and distinctive.',
    price: 130,
    image: '/perfume-images/jpg-le-male-essence.jpg',
    rating: 4.4,
    reviewCount: 2876,
    gender: 'men',
    seasons: ['autumn', 'winter'],
    occasions: ['evening', 'formal', 'date'],
    longevity: 'long-lasting',
    sillage: 'strong',
    concentration: 'edp',
    releaseYear: 2016,
    perfumer: 'Francis Kurkdjian',
    size: 75,
    inStock: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z'
  },
  // â”€â”€ Parfums de Marly top 3 â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  {
    id: '37',
    name: 'Layton',
    brand: 'Parfums de Marly',
    category: 'oriental',
    notes: {
      top: ['Bergamot', 'Lavender', 'Apple', 'Mandarin Orange'],
      middle: ['Violet', 'Jasmine', 'Geranium'],
      base: ['Guaiac Wood', 'Patchouli', 'Sandalwood', 'Cardamom', 'Vanilla', 'Pepper']
    },
    accords: [
      { name: 'warm spicy', intensity: 100, color: '#E67E22' },
      { name: 'woody', intensity: 85, color: '#8B4513' },
      { name: 'floral', intensity: 70, color: '#E9C46A' },
      { name: 'sweet', intensity: 65, color: '#F1948A' },
      { name: 'citrus', intensity: 55, color: '#FEE440' }
    ],
    description: 'The undisputed king of Parfums de Marly. A magnetic apple-lavender opening leads into a warm, spicy-woody heart â€” versatile, elegant, and a guaranteed compliment-puller.',
    price: 225,
    image: '/perfume-images/pdm-layton.jpg',
    rating: 4.9,
    reviewCount: 12543,
    gender: 'unisex',
    seasons: ['autumn', 'winter', 'spring'],
    occasions: ['office', 'formal', 'date', 'casual'],
    longevity: 'eternal',
    sillage: 'enormous',
    concentration: 'edp',
    releaseYear: 2016,
    perfumer: 'Hamid Merati-Kashani',
    size: 125,
    inStock: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z'
  },
  {
    id: '38',
    name: 'Pegasus',
    brand: 'Parfums de Marly',
    category: 'fresh',
    notes: {
      top: ['Heliotrope', 'Cumin', 'Bergamot'],
      middle: ['Bitter Almond', 'Lavender', 'Jasmine'],
      base: ['Vanilla', 'Sandalwood', 'Amber']
    },
    accords: [
      { name: 'vanilla', intensity: 95, color: '#F4E4C1' },
      { name: 'powdery', intensity: 85, color: '#F5CBA7' },
      { name: 'fresh', intensity: 75, color: '#4ECDC4' },
      { name: 'sweet', intensity: 70, color: '#F1948A' }
    ],
    description: 'A soft, powdery-fresh masterpiece. Heliotrope and almond create a dreamy, almost edible quality over a warm vanilla-sandalwood base â€” clean, elegant, and universally loved.',
    price: 225,
    image: '/perfume-images/pdm-pegasus.jpg',
    rating: 4.8,
    reviewCount: 9876,
    gender: 'unisex',
    seasons: ['spring', 'summer', 'autumn'],
    occasions: ['casual', 'office', 'date'],
    longevity: 'long-lasting',
    sillage: 'strong',
    concentration: 'edp',
    releaseYear: 2011,
    perfumer: 'Hamid Merati-Kashani',
    size: 125,
    inStock: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z'
  },
  {
    id: '39',
    name: 'Herod',
    brand: 'Parfums de Marly',
    category: 'oriental',
    notes: {
      top: ['Cinnamon', 'Pepper'],
      middle: ['Tobacco', 'Vanilla', 'Osmanthus'],
      base: ['Sandalwood', 'Patchouli', 'Musk']
    },
    accords: [
      { name: 'tobacco', intensity: 100, color: '#7D5A3C' },
      { name: 'vanilla', intensity: 90, color: '#F4E4C1' },
      { name: 'warm spicy', intensity: 80, color: '#E67E22' },
      { name: 'woody', intensity: 70, color: '#8B4513' }
    ],
    description: 'A rich, smoky tobacco-vanilla masterpiece. Cinnamon and pepper open into a warm tobacco heart with creamy vanilla and sandalwood â€” bold, masculine, and deeply luxurious.',
    price: 225,
    image: '/perfume-images/pdm-herod.jpg',
    rating: 4.7,
    reviewCount: 7654,
    gender: 'men',
    seasons: ['autumn', 'winter'],
    occasions: ['evening', 'special', 'date'],
    longevity: 'eternal',
    sillage: 'strong',
    concentration: 'edp',
    releaseYear: 2012,
    perfumer: 'Hamid Merati-Kashani',
    size: 125,
    inStock: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z'
  },
  // â”€â”€ Individual additions â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  {
    id: '40',
    name: 'Tuxedo',
    brand: 'Yves Saint Laurent',
    category: 'oriental',
    notes: {
      top: ['Bergamot', 'Cardamom', 'Pink Pepper'],
      middle: ['Iris', 'Violet', 'Jasmine'],
      base: ['Vanilla', 'Sandalwood', 'Musk', 'Amber']
    },
    accords: [
      { name: 'powdery', intensity: 95, color: '#F5CBA7' },
      { name: 'floral', intensity: 85, color: '#E9C46A' },
      { name: 'vanilla', intensity: 80, color: '#F4E4C1' },
      { name: 'woody', intensity: 65, color: '#8B4513' }
    ],
    description: 'A sophisticated, powdery-floral fragrance from YSL\'s Le Vestiaire des Parfums. Iris and violet meet warm vanilla and sandalwood â€” elegant, refined, and effortlessly chic.',
    price: 250,
    image: '/perfume-images/ysl-tuxedo.jpg',
    rating: 4.5,
    reviewCount: 2134,
    gender: 'unisex',
    seasons: ['autumn', 'winter', 'spring'],
    occasions: ['formal', 'evening', 'date'],
    longevity: 'long-lasting',
    sillage: 'moderate',
    concentration: 'edp',
    releaseYear: 2021,
    perfumer: 'Dora Baghriche',
    size: 125,
    inStock: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z'
  },
  {
    id: '41',
    name: 'Hacivat',
    brand: 'Nishane',
    category: 'chypre',
    notes: {
      top: ['Pineapple', 'Bergamot', 'Pink Pepper'],
      middle: ['Jasmine', 'Oakmoss', 'Patchouli'],
      base: ['Ambergris', 'Musk', 'Vetiver', 'Sandalwood']
    },
    accords: [
      { name: 'fruity', intensity: 95, color: '#FF6B6B' },
      { name: 'woody', intensity: 85, color: '#8B4513' },
      { name: 'fresh', intensity: 75, color: '#4ECDC4' },
      { name: 'musky', intensity: 70, color: '#C8B6E2' }
    ],
    description: 'A Turkish niche masterpiece. Pineapple and bergamot open into a lush oakmoss-patchouli heart with a deep ambergris base â€” complex, long-lasting, and utterly unique.',
    price: 295,
    image: '/perfume-images/nishane-hacivat.jpg',
    rating: 4.8,
    reviewCount: 5432,
    gender: 'unisex',
    seasons: ['spring', 'summer', 'autumn'],
    occasions: ['casual', 'date', 'special'],
    longevity: 'eternal',
    sillage: 'enormous',
    concentration: 'parfum',
    releaseYear: 2017,
    perfumer: 'Nishane',
    size: 100,
    inStock: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z'
  },
  {
    id: '42',
    name: '1 Million',
    brand: 'Paco Rabanne',
    category: 'oriental',
    notes: {
      top: ['Blood Mandarin', 'Grapefruit', 'Mint'],
      middle: ['Rose', 'Cinnamon', 'Spices'],
      base: ['Leather', 'Amber', 'Patchouli', 'Blond Wood']
    },
    accords: [
      { name: 'warm spicy', intensity: 100, color: '#E67E22' },
      { name: 'leather', intensity: 85, color: '#7D5A3C' },
      { name: 'citrus', intensity: 75, color: '#FEE440' },
      { name: 'amber', intensity: 70, color: '#F4A261' }
    ],
    description: 'One of the best-selling men\'s fragrances in the world. Bold blood mandarin and spices open into a rich leather-amber base â€” flashy, confident, and unmistakably iconic.',
    price: 110,
    image: '/perfume-images/paco-rabanne-1-million.jpg',
    rating: 4.6,
    reviewCount: 28765,
    gender: 'men',
    seasons: ['autumn', 'winter'],
    occasions: ['evening', 'date', 'special'],
    longevity: 'long-lasting',
    sillage: 'strong',
    concentration: 'edt',
    releaseYear: 2008,
    perfumer: 'Christophe Raynaud',
    size: 100,
    inStock: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z'
  }
];

module.exports = { mockPerfumes };
